// Generated by gencpp from file acri_localisation/railPair.msg
// DO NOT EDIT!


#ifndef ACRI_LOCALISATION_MESSAGE_RAILPAIR_H
#define ACRI_LOCALISATION_MESSAGE_RAILPAIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <acri_localisation/railLine.h>
#include <acri_localisation/railLine.h>
#include <acri_localisation/railLine.h>

namespace acri_localisation
{
template <class ContainerAllocator>
struct railPair_
{
  typedef railPair_<ContainerAllocator> Type;

  railPair_()
    : line1()
    , line2()
    , midline()  {
    }
  railPair_(const ContainerAllocator& _alloc)
    : line1(_alloc)
    , line2(_alloc)
    , midline(_alloc)  {
  (void)_alloc;
    }



   typedef  ::acri_localisation::railLine_<ContainerAllocator>  _line1_type;
  _line1_type line1;

   typedef  ::acri_localisation::railLine_<ContainerAllocator>  _line2_type;
  _line2_type line2;

   typedef  ::acri_localisation::railLine_<ContainerAllocator>  _midline_type;
  _midline_type midline;





  typedef boost::shared_ptr< ::acri_localisation::railPair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acri_localisation::railPair_<ContainerAllocator> const> ConstPtr;

}; // struct railPair_

typedef ::acri_localisation::railPair_<std::allocator<void> > railPair;

typedef boost::shared_ptr< ::acri_localisation::railPair > railPairPtr;
typedef boost::shared_ptr< ::acri_localisation::railPair const> railPairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acri_localisation::railPair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acri_localisation::railPair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acri_localisation::railPair_<ContainerAllocator1> & lhs, const ::acri_localisation::railPair_<ContainerAllocator2> & rhs)
{
  return lhs.line1 == rhs.line1 &&
    lhs.line2 == rhs.line2 &&
    lhs.midline == rhs.midline;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acri_localisation::railPair_<ContainerAllocator1> & lhs, const ::acri_localisation::railPair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acri_localisation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::acri_localisation::railPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acri_localisation::railPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acri_localisation::railPair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acri_localisation::railPair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acri_localisation::railPair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acri_localisation::railPair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acri_localisation::railPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d47e372c1831bf7059fde9b5559b9f11";
  }

  static const char* value(const ::acri_localisation::railPair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd47e372c1831bf70ULL;
  static const uint64_t static_value2 = 0x59fde9b5559b9f11ULL;
};

template<class ContainerAllocator>
struct DataType< ::acri_localisation::railPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acri_localisation/railPair";
  }

  static const char* value(const ::acri_localisation::railPair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acri_localisation::railPair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acri_localisation/railLine line1\n"
"acri_localisation/railLine line2\n"
"acri_localisation/railLine midline\n"
"================================================================================\n"
"MSG: acri_localisation/railLine\n"
"geometry_msgs/Point point1\n"
"geometry_msgs/Point point2\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acri_localisation::railPair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acri_localisation::railPair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.line1);
      stream.next(m.line2);
      stream.next(m.midline);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct railPair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acri_localisation::railPair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acri_localisation::railPair_<ContainerAllocator>& v)
  {
    s << indent << "line1: ";
    s << std::endl;
    Printer< ::acri_localisation::railLine_<ContainerAllocator> >::stream(s, indent + "  ", v.line1);
    s << indent << "line2: ";
    s << std::endl;
    Printer< ::acri_localisation::railLine_<ContainerAllocator> >::stream(s, indent + "  ", v.line2);
    s << indent << "midline: ";
    s << std::endl;
    Printer< ::acri_localisation::railLine_<ContainerAllocator> >::stream(s, indent + "  ", v.midline);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACRI_LOCALISATION_MESSAGE_RAILPAIR_H
