// Generated by gencpp from file acri_localisation/railLineVector.msg
// DO NOT EDIT!


#ifndef ACRI_LOCALISATION_MESSAGE_RAILLINEVECTOR_H
#define ACRI_LOCALISATION_MESSAGE_RAILLINEVECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <acri_localisation/railLine.h>

namespace acri_localisation
{
template <class ContainerAllocator>
struct railLineVector_
{
  typedef railLineVector_<ContainerAllocator> Type;

  railLineVector_()
    : header()
    , lines()  {
    }
  railLineVector_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::acri_localisation::railLine_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::acri_localisation::railLine_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;





  typedef boost::shared_ptr< ::acri_localisation::railLineVector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acri_localisation::railLineVector_<ContainerAllocator> const> ConstPtr;

}; // struct railLineVector_

typedef ::acri_localisation::railLineVector_<std::allocator<void> > railLineVector;

typedef boost::shared_ptr< ::acri_localisation::railLineVector > railLineVectorPtr;
typedef boost::shared_ptr< ::acri_localisation::railLineVector const> railLineVectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acri_localisation::railLineVector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acri_localisation::railLineVector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acri_localisation::railLineVector_<ContainerAllocator1> & lhs, const ::acri_localisation::railLineVector_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lines == rhs.lines;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acri_localisation::railLineVector_<ContainerAllocator1> & lhs, const ::acri_localisation::railLineVector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acri_localisation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::acri_localisation::railLineVector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acri_localisation::railLineVector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acri_localisation::railLineVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acri_localisation::railLineVector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acri_localisation::railLineVector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acri_localisation::railLineVector_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acri_localisation::railLineVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61e2ffd9765f40d10071b4476bd6929a";
  }

  static const char* value(const ::acri_localisation::railLineVector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61e2ffd9765f40d1ULL;
  static const uint64_t static_value2 = 0x0071b4476bd6929aULL;
};

template<class ContainerAllocator>
struct DataType< ::acri_localisation::railLineVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acri_localisation/railLineVector";
  }

  static const char* value(const ::acri_localisation::railLineVector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acri_localisation::railLineVector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"acri_localisation/railLine[] lines\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: acri_localisation/railLine\n"
"geometry_msgs/Point point1\n"
"geometry_msgs/Point point2\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::acri_localisation::railLineVector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acri_localisation::railLineVector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct railLineVector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acri_localisation::railLineVector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acri_localisation::railLineVector_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::acri_localisation::railLine_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACRI_LOCALISATION_MESSAGE_RAILLINEVECTOR_H
